name: Locust Load API Testing Report for Booking Endpoints

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Load Tests for Booking User Flow
        env:
          TOKEN_URL: ${{ secrets.TOKEN_URL }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          mkdir -p reports
          locust --headless -u 10 -t 20s --html reports/index.html
          echo "Locust tests completed."
          ls -la reports/
        continue-on-error: true 

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: locust-report
          path: reports/  # Upload the entire reports directory

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: behave-report
          path: ./reports  # Download to the reports directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          exclude_assets: .github
